# add handy aliases for ls
if [ -x /usr/bin/dircolors ]; then
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# some cds & moar lists
alias ..='cd ..'
alias .='ls -A'
# cd into dotfiles directory
alias 46='code \&c/46' # work mac, at least
# cd into whatever code directory is specified as my recent focus
alias focus='cd "$RECENT_FOCUS"'

# grep but with color!
alias grep='grep --color=always'
alias grepp='grep -nri' # my std flags
alias ungrep='grep -v'
alias @@='grep --exclude=\*.min.\*'
alias @='@@ --exclude=\*/{css,js}/\* -nri'
# you're so vain / you probably think this grep is about you
# TODONE move to git instead (my only use case, output adjustments, dynamic user?)
alias me='grep -i katie'

# Open in chrome
alias chrome='open -a "Google Chrome"'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Virtalenv(wrapper)
alias v='workon'
alias v.mk='mkvirtualenv'
alias v.ex='deactivate'

# FUNCTIONS

# cd into ~/Code/ with optional arg for further delving
code ()
{
  # TODO tab/autocomplete for dirs?
  cd ~/Code/"${1}"
}

# shortcut my preferred grep flags, plus switch arg order (dir before pattern),
# e.g., for multiple searches in the same place quickly/easily
grepper ()
{
  # # wildcard with grep
  # if [[ $1 == *"*"* ]]
  # then
  #   $GREPPATH="--include=\"$1\" ."
  # else
  #   $GREPPATH="$1"
  # fi

  # p.s. grepper is one final "g" away from being a palindrome, which is fun.
  grepp "$2" "$1"
}

# find the processes running on the specified port
portcullis ()
{
  lsof -i tcp:"$1"
}

# bower: uninstall package, clear cache, and reinstall package (with pkg name
# or a URL/local filepath), e.g., $ bower-reinstall local-package /path/to/pkg
bower-reinstall ()
{
  bower uninstall "$1" && bower cache clean && bower install "${2:-$1}"
}

# NOTE moving to bash script git alias
# # git: rebase to root, squashing all commits to a single one
# # with the message given by the user, e.g., $ git-reboot "Starting fresh"
# git-reboot ()
# {
#   git reset $(git commit-tree HEAD^{tree} -m "$1")
# }
