# Some applications read the EDITOR variable to determine your favourite text
# editor. So uncomment the line below and enter the editor of your choice :-)
#export EDITOR=/usr/bin/vim
#export EDITOR=/usr/bin/mcedit

test -s ~/.alias && . ~/.alias || true


[[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*


# Include GIT auto-completion script if it exists
# Note: This sort of thing is included in older systems
# Comment out unless we know we need it or can decide when to include
# [ -f ~/.git-completion.bash ] && source ~/.git-completion.bash

#
# Set up common aliases and enviornment variables
#

# alias mount-ostcdata="sudo mkdir /mnt/ostcdata; sudo mount -o vers=3 ostcrrhv02:/ostcdata /mnt/ostcdata"
# alias openssl-scx="openssl x509 -noout -in /etc/opt/microsoft/scx/ssl/scx.pem -subject -issuer"

# List of systems used for development purposes
#   PRIMARY_SYSTEM:	Primary development system (source for .teamprise files, etc)
#   DEVELOPMENT_LIST:	List of development systems (with teamprise enlistments)
#   SYSTEM_LIST:	Complete list of systems with certificates (no enlistments needed)

declare -a DEVELOPMENT_LIST SYSTEM_LIST

# Random other aliases and enviornment variables

IGNOREEOF=3

alias file_manager="nautilus --no-desktop"

#
# Platform specific setup
#

# Save path so, if we re-run ourselves, the path doesn't get needlessly long

if [ "${SAVED_PATH:-==Unset==}" = "==Unset==" ]; then
    export SAVED_PATH="${PATH}"
else
    export PATH="${SAVED_PATH}"
fi

# Some systems have less, some don't - if we don't, just use more

if ( type less > /dev/null 2>&1 ); then
    export LESS="-ImRs"
    export PAGER="less"
else
    alias less="more"
    export MORE="-is"
fi

# For 'ls', use colors if we have them (and use LS_OPTIONS if it exists)

if [ $(uname -s) = "Linux" -a -f /etc/SuSE-release ]; then
    if [ "${LS_OPTIONS}" != "" ]; then
  export LS_OPTIONS="${LS_OPTIONS} -p"
    else
  alias ls="ls -N --color=tty -T 0 -p"
    fi
else
    alias ls="ls -p"
fi

# Generic settings by O/S

export PATH=/usr/local/bin:$PATH

# Some additional path stuff

if [ -f /opt/git/bin/git ]; then
    export PATH=/opt/git/bin:${PATH}
    unset SSH_ASKPASS
fi

# if [ -f ~/Code/ ]; then
#     export PATH=~/Code:$PATH
# fi

# Support for rbenv
if [ -d ~/.rbenv ]; then
    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
fi


export PATH=.:~/bin:${PATH}

#
# Functions
#

# Function: global_find
#
# Search for a string globally throughout a directory structure
#
# Parameters:
#   String to search	(Typically quoted) String to search for
#   Search Path		Directory search path to begin searching at

global_find_usage()
{
    echo "Usage: global_find <search-string> <search-path>" 1>&2
}

global_find()
{
    if [ -z "${1}" -o -z "${2}" ]; then
  global_find_usage
  return 1;
    fi

    echo "Starting search for string \"$1\" in file path \"$2\" ..."

    # Only Linux appears to have '-0' for xargs ...
    if [ $(uname -s) = "Linux" ]; then
  find $2 -type f -print0 | xargs -0 grep -i "$1"
    else
  find $2 -type f | xargs grep -i "$1"
    fi
}
